### PR TITLE
added __init__.py

### PR DESCRIPTION
**Pull request by yagicandegirmenci**
Added __init__.py to the tests folder.

### CODE REVIEW

**Comment by MrNaif2018** [comment]
Hello! Thank you for your PR! But is `__init__.py` needed in tests folder? It is not going to be imported directly, but scanned by pytest (all `test_*.py` files in tests directory) automatically. Is there any specific reason to add `__init__.py`?

**Comment by yagicandegirmenci** [comment]
Its best practice to add `__init__.py`  but also There are veritable use cases for this - such as yours, your tests are working on your submodules that has `__init__.py` , not your installed package. If there are any errors in your installation procedure, testing will not catch it.

[Check this link out!](https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code)

**Comment by MrNaif2018** [comment]
Oh, I see. So if we would have had same file names it would error out. But I guess `__init__.py` should be added to coins directory too then?

**Comment by yagicandegirmenci** [comment]
Yeap, you should add  `__init__.py` to the coins.

**Comment by yagicandegirmenci** [comment]
Thanks @MrNaif2018 , i would be honored to be part of the list.

**Comment by MrNaif2018** [comment]
Done! Thank you again! Looking forward to see you contributing to BitcartCC in future!

**Pull request merged**
